"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    careeronestop.org API (careeronestop_org_api)
ID:     00e357bc-4084-4a64-8666-7e753b59ce13
Engine: parse_sdk 0.2.0
Generated at: 2026-09-12T14:28:52.694143+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Sex(str, enum.Enum):
    MALE = 'male'
    FEMALE = 'female'


class Sort(str, enum.Enum):
    NAME_ASC = 'name_asc'
    NAME_DESC = 'name_desc'
    AMOUNT_ASC = 'amount_asc'
    AMOUNT_DESC = 'amount_desc'
    DEADLINE_ASC = 'deadline_asc'
    DEADLINE_DESC = 'deadline_desc'


class AwardType(str, enum.Enum):
    LOAN = 'loan'
    GRANT = 'grant'
    PRIZE = 'prize'
    FELLOWSHIP = 'fellowship'
    SCHOLARSHIP = 'scholarship'
    PUBLIC_GRANT = 'public_grant'


class Affiliation(str, enum.Enum):
    VETERAN = 'veteran'
    DISABLED = 'disabled'
    MILITARY = 'military'
    MINORITY = 'minority'
    UNIVERSITY = 'university'
    ASIAN_AMERICAN = 'asian_american'
    NATIVE_AMERICAN = 'native_american'
    AFRICAN_AMERICAN = 'african_american'
    HISPANIC_AMERICAN = 'hispanic_american'
    UNION_AFFILIATION = 'union_affiliation'
    EMPLOYER_AFFILIATION = 'employer_affiliation'
    ACCREDITED_UNIVERSITY = 'accredited_university'
    RELIGIOUS_AFFILIATION = 'religious_affiliation'
    ASSOCIATION_MEMBERSHIP = 'association_membership'
    ETHNIC_GROUP_MEMBERSHIP = 'ethnic_group_membership'
    FRATERNAL_ORGANIZATION_MEMBERSHIP = 'fraternal_organization_membership'


class LevelOfStudy(str, enum.Enum):
    GRADUATE = 'graduate'
    ASSOCIATE = 'associate'
    BACHELORS = 'bachelors'
    VOCATIONAL = 'vocational'
    HIGH_SCHOOL = 'high_school'
    PROFESSIONAL_DEVELOPMENT = 'professional_development'


class InputFormatInvalid(_ParseError):
    """
    A parameter value has an invalid format
    """

    def __init__(self, status_code: int = 0, message: str = '', body: Any = None) -> None:
        super().__init__(status_code, message, body=body)


class ScholarshipNotFound(_ParseError):
    """
    The requested scholarship_id does not match any known award
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'scholarship_id': 'scholarship_id'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, scholarship_id: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.scholarship_id = scholarship_id


class Scholarship(_Resource):
    award_amount: Optional[str]
    award_types: List[str]
    criteria: Optional[str]
    deadline: Optional[str]
    duration: Optional[str]
    emails: List[str]
    focus: Optional[str]
    levels_of_study: List[str]
    more_information_url: Optional[str]
    name: str
    number_of_awards: Optional[str]
    organization: str
    organization_address: Optional[str]
    phone: Optional[str]
    purpose: Optional[str]
    qualifications: Optional[str]
    scholarship_id: str
    to_apply: Optional[str]
    url: str
    _RESOURCE_NAME = 'Scholarship'
    _KEY_FIELD = 'scholarship_id'

    def refresh(self) -> Scholarship:
        """
        Returns the full record for one award identified by scholarship_id from search_scholarships.scholarships[*].scholarship_id: name, organization and address, phone, emails, levels of study, award types, purpose, focus, qualifications (eligibility), selection criteria, award amount, number of awards, duration, how to apply, deadline (as written by the sponsor, e.g. a month and day), and the sponsor's website. Fields the sponsor did not supply are null (or an empty array for list fields). An unknown scholarship_id yields a stale_input / input_not_found error. One round trip per call.
        """
        _params: Dict[str, Any] = {}
        _params['scholarship_id'] = self.scholarship_id
        
        _resp = self._api._request('GET', 'get_scholarship', _params)
        return _coerce(_resp, 'Scholarship', self, mode='return')

class ScholarshipSummary(_Resource):
    award_amount: Optional[str]
    award_types: List[str]
    deadline: Optional[str]
    levels_of_study: List[str]
    name: str
    organization: str
    purpose: str
    scholarship_id: str
    url: str
    _RESOURCE_NAME = 'ScholarshipSummary'
    _KEY_FIELD = 'scholarship_id'

    def details(self) -> Scholarship:
        """
        Returns the full record for one award identified by scholarship_id from search_scholarships.scholarships[*].scholarship_id: name, organization and address, phone, emails, levels of study, award types, purpose, focus, qualifications (eligibility), selection criteria, award amount, number of awards, duration, how to apply, deadline (as written by the sponsor, e.g. a month and day), and the sponsor's website. Fields the sponsor did not supply are null (or an empty array for list fields). An unknown scholarship_id yields a stale_input / input_not_found error. One round trip per call.
        """
        _params: Dict[str, Any] = {}
        _params['scholarship_id'] = self.scholarship_id
        
        _resp = self._api._request('GET', 'get_scholarship', _params)
        return _coerce(_resp, 'Scholarship', self, mode='return')

class CareerOneStopScholarshipsCollection(_Collection):
    def get(self, scholarship_id: str) -> Scholarship:
        """
        Returns the full record for one award identified by scholarship_id from search_scholarships.scholarships[*].scholarship_id: name, organization and address, phone, emails, levels of study, award types, purpose, focus, qualifications (eligibility), selection criteria, award amount, number of awards, duration, how to apply, deadline (as written by the sponsor, e.g. a month and day), and the sponsor's website. Fields the sponsor did not supply are null (or an empty array for list fields). An unknown scholarship_id yields a stale_input / input_not_found error. One round trip per call.

        Args:
            scholarship_id: Numeric award identifier, exactly as emitted in search_scholarships.scholarships[*].scholarship_id.
        """
        _params: Dict[str, Any] = {}
        if scholarship_id is not None: _params['scholarship_id'] = scholarship_id
        
        _resp = self._api._request('GET', 'get_scholarship', _params)
        return _coerce(_resp, 'Scholarship', self, mode='return')

class CareerOneStopScholarshipSummariesCollection(_Collection):
    def search(self, affiliation: Optional[Affiliation | Literal['veteran', 'disabled', 'military', 'minority', 'university', 'asian_american', 'native_american', 'african_american', 'hispanic_american', 'union_affiliation', 'employer_affiliation', 'accredited_university', 'religious_affiliation', 'association_membership', 'ethnic_group_membership', 'fraternal_organization_membership']] = None, award_type: Optional[AwardType | Literal['loan', 'grant', 'prize', 'fellowship', 'scholarship', 'public_grant']] = None, keyword: Optional[str] = None, level_of_study: Optional[LevelOfStudy | Literal['graduate', 'associate', 'bachelors', 'vocational', 'high_school', 'professional_development']] = None, page_size: Optional[int] = None, residence_location: Optional[str] = None, sex: Optional[Sex | Literal['male', 'female']] = None, sort: Optional[Sort | Literal['name_asc', 'name_desc', 'amount_asc', 'amount_desc', 'deadline_asc', 'deadline_desc']] = None, study_location: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[ScholarshipSummary]:
        """
        Searches the scholarship catalog and returns one page of award summaries (name, organization, purpose, levels of study, award types, award amount, deadline month, canonical scholarship_id and detail URL). All filters combine with AND. Results are paged: page (1-based, default 1) and page_size (10, 25 or 50; default 10) are the caller's paging controls; total is the site's reported match count (the unfiltered catalog reports a maximum of 10,000) and has_more tells whether a further page exists. A combination of filters that matches nothing returns total 0 and an empty scholarships array (success). One round trip per call.

        Args:
            affiliation: Required affiliation or group membership the award is restricted to. Omitted = no affiliation filter.
            award_type: Kind of financial award. Omitted = all award types.
            keyword: Free-text keyword matched against award name, organization and purpose (e.g. nursing). Omitted = no keyword filter.
            level_of_study: Level of study the award supports. Omitted = all levels.
            page_size: Awards per page; the site accepts 10, 25 or 50 and other values are rejected.
            residence_location: Where the applicant lives, as the site labels it: US, International, or a full US state/territory name such as Ohio or District of Columbia. Passed to the site as written; an unknown value yields an empty result. Omitted = no residence restriction filter.
            sex: Sex-specific restriction of the award. Omitted = awards open to any sex plus sex-specific ones.
            sort: Result ordering.
            study_location: Where the applicant will study, as the site labels it: US, International, or a full US state/territory name such as Texas. Passed to the site as written; an unknown value yields an empty result. Omitted = no study-place filter.
        """
        _params: Dict[str, Any] = {}
        if affiliation is not None: _params['affiliation'] = affiliation
        if award_type is not None: _params['award_type'] = award_type
        if keyword is not None: _params['keyword'] = keyword
        if level_of_study is not None: _params['level_of_study'] = level_of_study
        if page_size is not None: _params['page_size'] = page_size
        if residence_location is not None: _params['residence_location'] = residence_location
        if sex is not None: _params['sex'] = sex
        if sort is not None: _params['sort'] = sort
        if study_location is not None: _params['study_location'] = study_location
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _page = _cursor if isinstance(_cursor, int) else 1
            _p['page'] = _page
            _resp = self._api._request('GET', 'search_scholarships', _p)
            items = _extract_items(_resp, 'scholarships')
            _resp = _resp if isinstance(_resp, dict) else {}
            _total = None
            try: _cur = int(_resp.get('page', _page))
            except (TypeError, ValueError): _cur = None
            if not items: nxt = None
            elif _total is not None and _cur is not None and (_cur - 1 + 1) >= _total: nxt = None
            else: nxt = (_cur + 1) if _cur is not None else (_page + 1)
            return ([_coerce(_i, 'ScholarshipSummary', self, mode='element') for _i in items], nxt)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Scholarship': Scholarship,
    'ScholarshipSummary': ScholarshipSummary,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class CareerOneStop(_BaseAPI):
    """
    Search the CareerOneStop Scholarship Finder (10,000+ scholarships, fellowships, grants, prizes and loans) by keyword, level of study, award type, residence and study location, required affiliation and sex, and retrieve full detail (amount, deadline, qualifications, contact, website) for a single award.
    """
    SCRAPER_ID: ClassVar[str] = '00e357bc-4084-4a64-8666-7e753b59ce13'
    PINNED_VERSION: ClassVar[Optional[int]] = 1
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_format_invalid': InputFormatInvalid, 'input_not_found': ScholarshipNotFound}

    @property
    def scholarships(self) -> 'CareerOneStopScholarshipsCollection':
        return CareerOneStopScholarshipsCollection(_api=self, _parent=None)

    @property
    def scholarship_summaries(self) -> 'CareerOneStopScholarshipSummariesCollection':
        return CareerOneStopScholarshipSummariesCollection(_api=self, _parent=None)

__all__ = [
    'CareerOneStop',
    'Scholarship',
    'ScholarshipSummary',
    'Sex',
    'Sort',
    'AwardType',
    'Affiliation',
    'LevelOfStudy',
    'InputFormatInvalid',
    'ScholarshipNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
