# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: CareerOneStop Scholarship Finder — bounded, re-runnable."""
from parse_apis.careeronestop_org_api import (
    CareerOneStop, LevelOfStudy, Sex, Sort, ScholarshipNotFound,
)

client = CareerOneStop()

# Search for nursing scholarships aimed at female graduate students.
for summary in client.scholarship_summaries.search(
    keyword="nursing",
    level_of_study=LevelOfStudy.GRADUATE,
    sex=Sex.FEMALE,
    sort=Sort.DEADLINE_ASC,
    limit=5,
):
    print(summary.name, "|", summary.organization, "|", summary.award_amount)

# Drill into the first hit for full detail (qualifications, how to apply, etc.).
hit = client.scholarship_summaries.search(
    keyword="nursing",
    level_of_study=LevelOfStudy.GRADUATE,
    limit=1,
).first()

if hit is not None:
    detail = hit.details()
    print(detail.name)
    print("Amount:", detail.award_amount)
    print("Qualifications:", detail.qualifications)
    print("Deadline:", detail.deadline)
    print("Emails:", detail.emails)

    # Same record reachable by direct ID lookup.
    try:
        same = client.scholarships.get(scholarship_id=hit.scholarship_id)
        print("Direct lookup:", same.name, "| Focus:", same.focus)
    except ScholarshipNotFound:
        print("Scholarship no longer available")

print("exercised: scholarship_summaries.search / details / scholarships.get")
