"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    phdscanner.com API (phdscanner_com_api)
ID:     7939701b-6ecc-48e4-8084-b024250fa10c
Engine: parse_sdk 0.2.0
Generated at: 2026-09-05T14:48:37.113496+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Funded(str, enum.Enum):
    TRUE = 'true'

    @property
    def display(self) -> str:
        return _DISPLAYS_Funded.get(self.name, self.name)

_DISPLAYS_Funded = {
    'TRUE': 'true',
}


class OpportunityNotFound(_ParseError):
    """
    The opportunity ID does not exist or has been removed
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'opportunity_id': 'opportunity_id'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, opportunity_id: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.opportunity_id = opportunity_id


class Opportunity(_Resource):
    ai_summary: str
    category: str
    city: str
    closing_date: int
    country: str
    created_at: int
    department: str
    description: str
    fully_funded: bool
    funded_amount: str
    id: str
    opportunity_url: str
    status: str
    supervisor: str
    supervisor_url: str
    title: str
    university: str
    university_url: str
    views: str
    _RESOURCE_NAME = 'Opportunity'
    _KEY_FIELD = 'id'

class Posting(_Resource):
    ai_title: str
    content: str
    country: str
    created_at: int
    department: str
    id: str
    posting_date: int
    professor_linkedin_url: str
    professor_name: str
    professor_title: str
    university: str
    views: int
    _RESOURCE_NAME = 'Posting'
    _KEY_FIELD = 'id'

class PhDScannerOpportunitiesCollection(_Collection):
    def get(self, opportunity_id: str) -> Opportunity:
        """
        Get full details of a single PhD opportunity by its ID, including the complete HTML description, supervisor contact information, and application details.

        Args:
            opportunity_id: UUID of the PhD opportunity (from search_opportunities results).
        """
        _params: Dict[str, Any] = {}
        if opportunity_id is not None: _params['opportunity_id'] = opportunity_id
        
        _resp = self._api._request('GET', 'get_opportunity', _params)
        return _coerce(_resp, 'Opportunity', self, mode='return')
    def search(self, country: Optional[str] = None, funded: Optional[Funded | Literal['true']] = None, university: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Opportunity]:
        """
        Search PhD opportunities with optional filters for country, university, and funding status. Returns paginated results sorted by most recent. Each result includes title, university, location, discipline, supervisor, funding details, and an AI-generated summary.

        Args:
            country: Filter by country name (e.g. Germany, Netherlands, United Kingdom, Switzerland, Australia).
            funded: Filter for fully funded positions only. Pass 'true' to include only fully funded positions.
            university: Filter by university name (e.g. EPFL, University of Vienna, TU Dresden, Technical University of Munich).
        """
        _params: Dict[str, Any] = {}
        if country is not None: _params['country'] = country
        if funded is not None: _params['funded'] = funded
        if university is not None: _params['university'] = university
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'search_opportunities', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Opportunity', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class PhDScannerPostingsCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Posting]:
        """
        List PhD position postings shared by professors on LinkedIn. Returns professor details, university, department, and the post content.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'list_phd_postings', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Posting', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Opportunity': Opportunity,
    'Posting': Posting,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class PhDScanner(_BaseAPI):
    """
    Search and browse PhD opportunities and professor postings from PhDScanner.com
    """
    SCRAPER_ID: ClassVar[str] = '7939701b-6ecc-48e4-8084-b024250fa10c'
    PINNED_VERSION: ClassVar[Optional[int]] = 4
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': OpportunityNotFound}

    @property
    def opportunities(self) -> 'PhDScannerOpportunitiesCollection':
        return PhDScannerOpportunitiesCollection(_api=self, _parent=None)

    @property
    def postings(self) -> 'PhDScannerPostingsCollection':
        return PhDScannerPostingsCollection(_api=self, _parent=None)

__all__ = [
    'PhDScanner',
    'Opportunity',
    'Posting',
    'Funded',
    'OpportunityNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
