# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: PhDScanner SDK — search PhD opportunities and professor postings."""
from parse_apis.phdscanner_com_api import PhDScanner, Funded, OpportunityNotFound

client = PhDScanner()

# Search funded PhD positions in Germany
for opp in client.opportunities.search(country="Germany", funded=Funded.TRUE, limit=3):
    print(opp.title, "|", opp.university, "|", opp.department)

# Drill into a single opportunity for full details
opp = client.opportunities.search(country="Netherlands", limit=1).first()
if opp:
    detail = client.opportunities.get(opportunity_id=opp.id)
    print(detail.title, "|", detail.supervisor, "|", detail.fully_funded)

# Handle not-found errors gracefully
try:
    client.opportunities.get(opportunity_id="00000000-0000-0000-0000-000000000000")
except OpportunityNotFound as exc:
    print(f"Opportunity not found: {exc}")

# Browse professor PhD postings from LinkedIn
for posting in client.postings.list(limit=3):
    print(posting.ai_title, "|", posting.professor_name, "|", posting.university)

print("exercised: opportunities.search / opportunities.get / postings.list")
