"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    opportunitydesk.org API (opportunitydesk_org_api)
ID:     b5531142-2817-47a6-8a5a-c9b0f6954a30
Engine: parse_sdk 0.2.0
Generated at: 2026-09-12T14:08:29.042820+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class GrantNotFound(_ParseError):
    """
    The requested grant slug or ID does not match any grant
    """

    def __init__(self, status_code: int = 0, message: str = '', body: Any = None) -> None:
        super().__init__(status_code, message, body=body)


class Grant(_Resource):
    application_url: Optional[str]
    deadline: Optional[str]
    eligible_applicants: List[str]
    eligible_countries: List[str]
    grant_amount: Optional[str]
    grant_amount_details: Optional[List[str]]
    id: int
    link: str
    slug: str
    title: str
    _RESOURCE_NAME = 'Grant'
    _KEY_FIELD = 'slug'

class GrantSummary(_Resource):
    date: datetime
    excerpt: str
    id: int
    link: str
    slug: str
    title: str
    _RESOURCE_NAME = 'GrantSummary'
    _KEY_FIELD = 'slug'

    def details(self) -> Grant:
        """
        Get detailed information about a specific grant by its slug or numeric ID. Parses the grant post content to extract structured fields: deadline, eligible countries, eligible applicants, grant amount, per-sector/individual amount details, and the external application URL. Provide either slug (from list_grants results) or id.
        """
        _params: Dict[str, Any] = {}
        _params['slug'] = self.slug
        
        _resp = self._api._request('GET', 'get_grant_details', _params)
        return _coerce(_resp, 'Grant', self, mode='return')

class OpportunityDeskGrantsCollection(_Collection):
    def get(self, slug: Optional[str] = None) -> Grant:
        """
        Get detailed information about a specific grant by its slug or numeric ID. Parses the grant post content to extract structured fields: deadline, eligible countries, eligible applicants, grant amount, per-sector/individual amount details, and the external application URL. Provide either slug (from list_grants results) or id.

        Args:
            slug: URL slug of the grant post (e.g. 'charity-accelerator-program-2026'). Obtain from list_grants results.
        """
        _params: Dict[str, Any] = {}
        if slug is not None: _params['slug'] = slug
        
        _resp = self._api._request('GET', 'get_grant_details', _params)
        return _coerce(_resp, 'Grant', self, mode='return')

class OpportunityDeskGrantSummariesCollection(_Collection):
    def list(self, per_page: Optional[int] = None, search: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[GrantSummary]:
        """
        List grant opportunities from Opportunity Desk with optional search filtering and pagination. Returns grant summaries including title, date, link, and excerpt. Pagination is controlled by page and per_page parameters.

        Args:
            per_page: Number of results per page (1-100).
            search: Free-text search query to filter grants by keyword.
        """
        _params: Dict[str, Any] = {}
        if per_page is not None: _params['per_page'] = per_page
        if search is not None: _params['search'] = search
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _page = _cursor if isinstance(_cursor, int) else 1
            _p['page'] = _page
            _resp = self._api._request('GET', 'list_grants', _p)
            items = _extract_items(_resp, 'grants')
            _resp = _resp if isinstance(_resp, dict) else {}
            _total = None
            _cur = _page
            if not items: nxt = None
            elif _total is not None and _cur is not None and (_cur - 1 + 1) >= _total: nxt = None
            else: nxt = (_cur + 1) if _cur is not None else (_page + 1)
            return ([_coerce(_i, 'GrantSummary', self, mode='element') for _i in items], nxt)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Grant': Grant,
    'GrantSummary': GrantSummary,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class OpportunityDesk(_BaseAPI):
    """
    Scrape grant opportunities from Opportunity Desk, including grant details such as deadlines, eligible countries, eligible applicants, grant amounts, and application URLs.
    """
    SCRAPER_ID: ClassVar[str] = 'b5531142-2817-47a6-8a5a-c9b0f6954a30'
    PINNED_VERSION: ClassVar[Optional[int]] = 1
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': GrantNotFound}

    @property
    def grants(self) -> 'OpportunityDeskGrantsCollection':
        return OpportunityDeskGrantsCollection(_api=self, _parent=None)

    @property
    def grant_summaries(self) -> 'OpportunityDeskGrantSummariesCollection':
        return OpportunityDeskGrantSummariesCollection(_api=self, _parent=None)

__all__ = [
    'OpportunityDesk',
    'Grant',
    'GrantSummary',
    'GrantNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
