# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: OpportunityDesk SDK — discover and inspect grant opportunities."""
from parse_apis.opportunitydesk_org_api import OpportunityDesk, GrantNotFound

client = OpportunityDesk()

# Search for climate-related grants, capped at 5 results.
for summary in client.grant_summaries.list(search="climate", per_page=5, limit=5):
    print(summary.title, "|", summary.date)

# Drill into the first result's full details via summary→detail navigation.
first = client.grant_summaries.list(search="climate", limit=1).first()
if first is not None:
    grant = first.details()
    print(grant.title)
    print("Deadline:", grant.deadline)
    print("Amount:", grant.grant_amount)
    print("Countries:", grant.eligible_countries)
    print("Apply:", grant.application_url)

# Point lookup by slug obtained from the summary.
if first is not None:
    try:
        detail = client.grants.get(slug=first.slug)
        print(detail.title, "—", detail.grant_amount)
    except GrantNotFound:
        print("Grant no longer available")

print("exercised: grant_summaries.list / details / grants.get")
