"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    mastersportal.com API (mastersportal_com_api)
ID:     cac76476-ffa7-4528-886c-5346d93f84db
Engine: parse_sdk 0.2.0
Generated at: 2026-09-12T14:08:29.039759+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class ScholarshipSearchError(_ParseError):
    """
    Invalid input parameters provided
    """

    def __init__(self, status_code: int = 0, message: str = '', body: Any = None) -> None:
        super().__init__(status_code, message, body=body)


class Scholarship(_Resource):
    id: str
    url: Optional[str]
    title: str
    deadline: Optional[str]
    description: str
    provider_id: str
    grant_amount: Optional[int]
    provider_name: str
    grant_currency: Optional[str]
    application_basis: Optional[str]
    grant_description: Optional[str]
    provider_location: Optional[str]
    benefits_description: Optional[str]
    destination_countries: Optional[str]
    provider_is_university: bool
    _RESOURCE_NAME = 'Scholarship'
    _KEY_FIELD = 'id'

class MastersportalScholarshipsCollection(_Collection):
    def search(self, discipline_id: Optional[str] = None, destination_country: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Search scholarships available on Mastersportal. Results are auto-iterated across pages. Supports filtering by destination country (ISO 2-letter code) and discipline ID. Returns scholarship title, description, provider, deadline, grant details, and a direct URL.

        Args:
            discipline_id: Numeric discipline ID to filter scholarships by field of study. Known IDs: 7 (Engineering & Technology), 13 (Business & Management), 10 (Computer Science & IT), 23 (Natural Sciences & Mathematics), 11 (Social Sciences), 24 (Humanities), 14 (Arts, Design & Architecture), 9 (Medicine & Health), 15 (Education & Training), 17 (Law), 12 (Environmental Studies & Earth Sciences), 16 (Agriculture & Forestry), 8 (Hospitality, Leisure & Sports), 22 (Journalism & Media), 19 (Applied Sciences & Professions).
            destination_country: ISO 3166-1 alpha-2 country code to filter scholarships by study destination (e.g. CA for Canada, US for United States, GB for United Kingdom, DE for Germany).
        """
        _params: Dict[str, Any] = {}
        if discipline_id is not None: _params['discipline_id'] = discipline_id
        if destination_country is not None: _params['destination_country'] = destination_country
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _page = _cursor if isinstance(_cursor, int) else 1
            _p['page'] = _page
            _resp = self._api._request('GET', 'search_scholarships', _p)
            items = _extract_items(_resp, 'scholarships')
            _resp = _resp if isinstance(_resp, dict) else {}
            _total = None
            try: _cur = int(_resp.get('page', _page))
            except (TypeError, ValueError): _cur = None
            if not items: nxt = None
            elif _total is not None and _cur is not None and (_cur - 1 + 1) >= _total: nxt = None
            else: nxt = (_cur + 1) if _cur is not None else (_page + 1)
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], nxt)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Scholarship': Scholarship,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class Mastersportal(_BaseAPI):
    """
    Search and browse scholarships from Mastersportal.com, with optional filters for destination country and academic discipline.
    """
    SCRAPER_ID: ClassVar[str] = 'cac76476-ffa7-4528-886c-5346d93f84db'
    PINNED_VERSION: ClassVar[Optional[int]] = 2
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_format_invalid': ScholarshipSearchError}

    @property
    def scholarships(self) -> 'MastersportalScholarshipsCollection':
        return MastersportalScholarshipsCollection(_api=self, _parent=None)

__all__ = [
    'Mastersportal',
    'Scholarship',
    'ScholarshipSearchError',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
