# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.

"""Walkthrough: Mastersportal Scholarships SDK — search, filter, and browse scholarships."""
from parse_apis.mastersportal_com_api import Mastersportal, ScholarshipSearchError

client = Mastersportal()

# Search all scholarships, limited to 5 results
for scholarship in client.scholarships.search(limit=5):
    print(scholarship.title, "|", scholarship.deadline, "|", scholarship.provider_name)

# Filter by destination country (Canada) and discipline (Engineering & Technology)
engineering_in_canada = client.scholarships.search(
    destination_country="CA",
    discipline_id="7",
    limit=3,
)
for s in engineering_in_canada:
    print(s.title, "-", s.grant_description, "-", s.destination_countries)

# Drill into first result
first = client.scholarships.search(destination_country="GB", limit=1).first()
if first:
    print(first.title, first.url, first.grant_amount, first.grant_currency)

# Handle errors for invalid input
try:
    bad = client.scholarships.search(destination_country="INVALID", limit=1).first()
except ScholarshipSearchError as exc:
    print(f"Search error: {exc}")

print("exercised: scholarships.search with filters, pagination, and error handling")
