"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    usnews.com API (usnews_com_api)
ID:     0a73de7e-3ca4-4503-abb8-d25b83995be5
Engine: parse_sdk 0.2.0
Generated at: 2026-09-13T01:55:03.766498+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class SortOption(str, enum.Enum):
    ALPHA_ASC = 'alpha-asc'
    ALPHA_DESC = 'alpha-desc'
    AMOUNT_ASC = 'amount-asc'
    BEST_MATCH = 'best-match'
    AMOUNT_DESC = 'amount-desc'
    DEADLINE_ASC = 'deadline-asc'
    DEADLINE_DESC = 'deadline-desc'


class InputFormatInvalid(_ParseError):
    """
    A request parameter has an invalid format
    """

    def __init__(self, status_code: int = 0, message: str = '', body: Any = None) -> None:
        super().__init__(status_code, message, body=body)


class Scholarship(_Resource):
    amount_interval: str
    average_award_amount: str
    deadline: str
    deadline_date: Optional[str]
    description: str
    eligibility_criteria: List[str]
    enrollment: str
    ethnicities: Optional[str]
    is_featured: bool
    majors: Optional[str]
    name: str
    program_url: str
    provider: str
    requirements: List[str]
    residency: str
    _RESOURCE_NAME = 'Scholarship'
    _KEY_FIELD = None

class USNewsScholarshipsCollection(_Collection):
    def search(self, keyword: Optional[str] = None, sort: Optional[SortOption | Literal['alpha-asc', 'alpha-desc', 'amount-asc', 'best-match', 'amount-desc', 'deadline-asc', 'deadline-desc']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Search scholarships by keyword with sorting and pagination. Returns up to 10-11 scholarships per page from a catalog of 13,000+. Each result includes award name, provider, description, amount, deadline, eligibility criteria (residency, enrollment, ethnicities, majors), and application requirements. When keyword is omitted, returns all scholarships. Results are paginated server-side; use the page parameter to iterate.

        Args:
            keyword: Free-text search keyword to filter scholarships (e.g. 'engineering', 'nursing'). Omitting returns all scholarships.
            sort: Sort order for results.
        """
        _params: Dict[str, Any] = {}
        if keyword is not None: _params['keyword'] = keyword
        if sort is not None: _params['sort'] = sort
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _page = _cursor if isinstance(_cursor, int) else 1
            _p['page'] = _page
            _resp = self._api._request('GET', 'search_scholarships', _p)
            items = _extract_items(_resp, 'scholarships')
            _resp = _resp if isinstance(_resp, dict) else {}
            try: _total = int(_resp.get('total_pages'))
            except (TypeError, ValueError): _total = None
            try: _cur = int(_resp.get('current_page', _page))
            except (TypeError, ValueError): _cur = None
            if not items: nxt = None
            elif _total is not None and _cur is not None and (_cur - 1 + 1) >= _total: nxt = None
            else: nxt = (_cur + 1) if _cur is not None else (_page + 1)
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], nxt)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Scholarship': Scholarship,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class USNews(_BaseAPI):
    """
    Search and browse scholarships from the US News & World Report Scholarship Finder, including eligibility criteria, award amounts, and deadlines.
    """
    SCRAPER_ID: ClassVar[str] = '0a73de7e-3ca4-4503-abb8-d25b83995be5'
    PINNED_VERSION: ClassVar[Optional[int]] = 1
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_format_invalid': InputFormatInvalid}

    @property
    def scholarships(self) -> 'USNewsScholarshipsCollection':
        return USNewsScholarshipsCollection(_api=self, _parent=None)

__all__ = [
    'USNews',
    'Scholarship',
    'SortOption',
    'InputFormatInvalid',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
