# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: US News Scholarship Finder — search, sort, and inspect results."""
from parse_apis.usnews_com_api import USNews, SortOption, InputFormatInvalid

client = USNews()

# Browse scholarships sorted by deadline, capped at 5 total results.
for scholarship in client.scholarships.search(sort=SortOption.DEADLINE_ASC, limit=5):
    print(scholarship.name, "|", scholarship.average_award_amount, "|", scholarship.deadline)

# Keyword search: find one engineering scholarship and inspect its details.
hit = client.scholarships.search(keyword="engineering", sort=SortOption.BEST_MATCH, limit=1).first()
if hit is not None:
    print(hit.name, "-", hit.provider)
    print("Residency:", hit.residency)
    print("Enrollment:", hit.enrollment)
    if hit.majors is not None:
        print("Majors:", hit.majors)
    for criterion in hit.eligibility_criteria:
        print(" •", criterion)

# Demonstrate typed error handling for an invalid sort value.
try:
    client.scholarships.search(sort="not-a-valid-sort", limit=1).first()
except InputFormatInvalid as e:
    print("Caught expected error:", e.message)

print("exercised: scholarships.search (browse + keyword + error handling)")
