"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    fastweb.com API (fastweb_com_api)
ID:     d73272bd-bc1f-4987-8927-3870cd569f5d
Engine: parse_sdk 0.2.0
Generated at: 2026-09-12T14:28:52.684215+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class Major(str, enum.Enum):
    BIOLOGY = 'Biology'
    NURSING = 'Nursing'
    BUSINESS = 'Business'
    ENGINEERING = 'Engineering'
    COMPUTER_SCIENCE = 'Computer Science'

    @property
    def display(self) -> str:
        return _DISPLAYS_Major.get(self.name, self.name)

_DISPLAYS_Major = {
    'BIOLOGY': 'Biology',
    'NURSING': 'Nursing',
    'BUSINESS': 'Business',
    'ENGINEERING': 'Engineering',
    'COMPUTER_SCIENCE': 'Computer Science',
}


class State(str, enum.Enum):
    TEXAS = 'Texas'
    FLORIDA = 'Florida'
    ILLINOIS = 'Illinois'
    NEW_YORK = 'New York'
    CALIFORNIA = 'California'

    @property
    def display(self) -> str:
        return _DISPLAYS_State.get(self.name, self.name)

_DISPLAYS_State = {
    'TEXAS': 'Texas',
    'FLORIDA': 'Florida',
    'ILLINOIS': 'Illinois',
    'NEW_YORK': 'New York',
    'CALIFORNIA': 'California',
}


class CategoryNotFound(_ParseError):
    """
    The category slug does not exist on Fastweb (404/410 response)
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'slug': 'slug'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, slug: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.slug = slug


class Article(_Resource):
    url: str
    title: str
    _RESOURCE_NAME = 'Article'
    _KEY_FIELD = 'url'

class Category(_Resource):
    url: str
    name: str
    slug: str
    _RESOURCE_NAME = 'Category'
    _KEY_FIELD = 'slug'

class Discount(_Resource):
    offer: str
    merchant: str
    _RESOURCE_NAME = 'Discount'
    _KEY_FIELD = 'merchant'

class Scholarship(_Resource):
    award: Optional[str]
    title: str
    deadline: Optional[str]
    provider: Optional[str]
    detail_url: Optional[str]
    _RESOURCE_NAME = 'Scholarship'
    _KEY_FIELD = None

class ScholarshipDetail(_Resource):
    url: str
    title: str
    details: Dict[str, str]
    provider: Optional[str]
    description: str
    _RESOURCE_NAME = 'ScholarshipDetail'
    _KEY_FIELD = 'url'

class FastwebArticlesCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Article]:
        """
        Returns recent financial aid articles from Fastweb covering topics like FAFSA, student loans, financial aid strategies, and loan forgiveness programs. No input parameters required.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_financial_aid_articles', _p)
            items = _extract_items(_resp, 'articles')
            return ([_coerce(_i, 'Article', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class FastwebCategoriesCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Category]:
        """
        Returns all browseable scholarship categories from the Fastweb directory page. Each category includes a name, slug, and URL. Use the slug with get_scholarships_by_category to retrieve scholarships in that category.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_scholarship_directory_categories', _p)
            items = _extract_items(_resp, 'categories')
            return ([_coerce(_i, 'Category', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class FastwebDiscountsCollection(_Collection):
    def list(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Discount]:
        """
        Returns available student discounts and deals from various merchants partnered with Fastweb. Each discount includes the merchant name and the offer description. No input parameters required.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_student_discounts', _p)
            items = _extract_items(_resp, 'discounts')
            return ([_coerce(_i, 'Discount', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class FastwebScholarshipsCollection(_Collection):
    def by_major(self, major: Major | Literal['Biology', 'Nursing', 'Business', 'Engineering', 'Computer Science'], limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Returns scholarships for a specific academic major or field of study. Constructs the directory slug from the major name (e.g. 'Engineering' becomes 'scholarships-for-engineering-majors'). Each scholarship includes title, provider, award amount, deadline, and detail_url.

        Args:
            major: Major or field of study name (e.g. 'Engineering', 'Computer Science', 'Nursing').
        """
        _params: Dict[str, Any] = {}
        if major is not None: _params['major'] = major
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_scholarships_by_major', _p)
            items = _extract_items(_resp, 'scholarships')
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)
    def by_state(self, state: State | Literal['Texas', 'Florida', 'Illinois', 'New York', 'California'], limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Returns scholarships specific to a U.S. state. Constructs the directory slug from the state name (e.g. 'California' becomes 'california-scholarships'). Each scholarship includes title, provider, award amount, deadline, and detail_url.

        Args:
            state: U.S. state name (e.g. 'California', 'New York', 'Texas').
        """
        _params: Dict[str, Any] = {}
        if state is not None: _params['state'] = state
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_scholarships_by_state', _p)
            items = _extract_items(_resp, 'scholarships')
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)
    def featured(self, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Returns currently featured and promoted scholarship opportunities from Fastweb's homepage. These are frequently updated sponsored listings. No input parameters required.
        """
        _params: Dict[str, Any] = {}
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_featured_scholarships', _p)
            items = _extract_items(_resp, 'scholarships')
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)
    def by_category(self, slug: str, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Returns scholarships for a specific category from the Fastweb directory. Accepts a category slug (obtainable from get_scholarship_directory_categories). Each scholarship includes title, provider, award amount, deadline, and a detail_url for use with get_scholarship_detail.

        Args:
            slug: Category slug from the directory. Obtain from get_scholarship_directory_categories or construct directly (e.g. 'scholarships-for-women', 'scholarships-for-adopted-students').
        """
        _params: Dict[str, Any] = {}
        if slug is not None: _params['slug'] = slug
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_scholarships_by_category', _p)
            items = _extract_items(_resp, 'scholarships')
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class FastwebScholarshipDetailsCollection(_Collection):
    def get(self, id_slug: str) -> ScholarshipDetail:
        """
        Returns comprehensive details for a specific scholarship including full description, award amount, deadline, awards available, and provider. The id_slug is the final path segment from a scholarship's detail_url (e.g. '77822-women-s-league-scholarship-uiuc').

        Args:
            id_slug: Scholarship ID and slug from a scholarship's detail_url field (e.g. '77822-women-s-league-scholarship-uiuc').
        """
        _params: Dict[str, Any] = {}
        if id_slug is not None: _params['id_slug'] = id_slug
        
        _resp = self._api._request('GET', 'get_scholarship_detail', _params)
        return _coerce(_resp, 'ScholarshipDetail', self, mode='return')

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Article': Article,
    'Category': Category,
    'Discount': Discount,
    'Scholarship': Scholarship,
    'ScholarshipDetail': ScholarshipDetail,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class Fastweb(_BaseAPI):
    """
    Browse and search scholarships by category, state, or major from Fastweb.com. Get detailed scholarship information, financial aid articles, and student discounts.
    """
    SCRAPER_ID: ClassVar[str] = 'd73272bd-bc1f-4987-8927-3870cd569f5d'
    PINNED_VERSION: ClassVar[Optional[int]] = 5
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': CategoryNotFound}

    @property
    def articles(self) -> 'FastwebArticlesCollection':
        return FastwebArticlesCollection(_api=self, _parent=None)

    @property
    def categories(self) -> 'FastwebCategoriesCollection':
        return FastwebCategoriesCollection(_api=self, _parent=None)

    @property
    def discounts(self) -> 'FastwebDiscountsCollection':
        return FastwebDiscountsCollection(_api=self, _parent=None)

    @property
    def scholarships(self) -> 'FastwebScholarshipsCollection':
        return FastwebScholarshipsCollection(_api=self, _parent=None)

    @property
    def scholarship_details(self) -> 'FastwebScholarshipDetailsCollection':
        return FastwebScholarshipDetailsCollection(_api=self, _parent=None)

__all__ = [
    'Fastweb',
    'Article',
    'Category',
    'Discount',
    'Scholarship',
    'ScholarshipDetail',
    'Major',
    'State',
    'CategoryNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
