# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
"""Walkthrough: Fastweb Scholarship API — discover scholarships by major, state, or category."""
from parse_apis.fastweb_com_api import Fastweb, Major, State, ScholarshipDetail, CategoryNotFound

client = Fastweb()

# Browse featured scholarships — quick overview of promoted opportunities.
for scholarship in client.scholarships.featured(limit=3):
    print(scholarship.title, scholarship.award, scholarship.deadline)

# Search by major using the Major enum for type safety.
eng = client.scholarships.by_major(major=Major.ENGINEERING, limit=1).first()
if eng:
    print(eng.title, eng.provider, eng.award)

# Search by state — find California-specific funding.
for s in client.scholarships.by_state(state=State.CALIFORNIA, limit=3):
    print(s.title, s.provider, s.deadline)

# Fetch full scholarship details by id_slug.
detail = client.scholarshipdetails.get(id_slug="191939-california-dream-act-service-incentive-grant-dsig")
print(detail.title, detail.provider, detail.description[:80])

# Typed error handling: catch a bad category slug.
try:
    for s in client.scholarships.by_category(slug="nonexistent-slug-xyz", limit=1):
        print(s.title)
except CategoryNotFound as exc:
    print(f"Category not found: {exc.slug}")

# Student discounts — browse available deals.
for discount in client.discounts.list(limit=3):
    print(discount.merchant, discount.offer)

print("exercised: scholarships.featured / by_major / by_state / scholarshipdetails.get / by_category / discounts.list")
