"""Auto-generated by `parse sync`. Do not edit by hand.

Source: https://api.parse.bot
API:    scholarshipportal.com API (scholarshipportal_com_api)
ID:     d8ac1888-45af-4a2b-9aee-a54938204f94
Engine: parse_sdk 0.2.0
Generated at: 2026-09-05T14:48:37.109251+00:00
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Literal, Optional, ClassVar

from parse_sdk._runtime import (
    ParseError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    BadRequestError,
    QuotaExceededError,
    RateLimitError,
    UpstreamError,
    PaginationError,
    PaginationLimitError,
)
# Runtime bases the GENERATED CODE subclasses-or-references by name are bound
# under reserved private aliases so a DOMAIN resource named ``Collection`` /
# ``Resource`` / ``Paginator`` / ``BaseAPI`` (or an error named ``ParseError``)
# cannot shadow the base it must derive from. Domain names and runtime-base
# names then live in disjoint namespaces — correct-by-construction. The bare
# error subclasses above (incl. the public base ``ParseError``) stay importable
# for user re-export; the generated code subclasses the ``_ParseError`` private
# alias below, so the disjoint-namespace invariant is untouched.
from parse_sdk._runtime import (
    BaseAPI as _BaseAPI,
    Collection as _Collection,
    Paginator as _Paginator,
    PaginationError as _PaginationError,
    ParseError as _ParseError,
    Resource as _Resource,
)


__generated_with__ = "0.2.0"

from parse_sdk._runtime import coerce as _runtime_coerce

def _coerce(value, type_label, ctx, mode='element'):
    # `ctx` is the calling object (resource instance or collection).
    # `mode` (S5) selects the return boundary: a single-resource return
    # emits mode='return' (strict husk/scalar fail-loud); per-element
    # paginator rows emit mode='element' (lenient degrade-to-raw, the
    # default). The strict verdict needs the return contract boundary,
    # so boundary is True exactly when mode=='return'.
    api = getattr(ctx, '_api', None) or (ctx if isinstance(ctx, _BaseAPI) else None)
    parent = ctx if not isinstance(ctx, _BaseAPI) else None
    return _runtime_coerce(value, type_label, resource_classes=_RESOURCE_CLASSES,
                           api=api, parent=parent, boundary=(mode == 'return'), mode=mode)


from parse_sdk._runtime import _extract_items


class StudyLevel(str, enum.Enum):
    PHD = 'phd'
    MASTER = 'master'
    BACHELOR = 'bachelor'


class ScholarshipNotFound(_ParseError):
    """
    The scholarship ID/slug combination does not exist (404 or 410 response)
    """

    _CARRY_PARAMS: ClassVar[Dict[str, str]] = {'id': 'id', 'slug': 'slug'}
    def __init__(self, status_code: int = 0, message: str = '', body: Any = None, id: Any = None, slug: Any = None) -> None:
        super().__init__(status_code, message, body=body)
        self.id = id
        self.slug = slug


class Grant(_Resource):
    amount: Optional[int]
    currency: Optional[str]
    description: Optional[str]
    _RESOURCE_NAME = 'Grant'
    _KEY_FIELD = None

class Country(_Resource):
    iso: str
    count: int
    _RESOURCE_NAME = 'Country'
    _KEY_FIELD = 'iso'

class Tuition(_Resource):
    amount: Optional[int]
    period: Optional[str]
    currency: Optional[str]
    _RESOURCE_NAME = 'Tuition'
    _KEY_FIELD = None

class Location(_Resource):
    city: Optional[str]
    country: Optional[str]
    country_iso: Optional[str]
    _RESOURCE_NAME = 'Location'
    _KEY_FIELD = None

class Provider(_Resource):
    id: str
    name: str
    location: Optional[str]
    is_university: bool
    _RESOURCE_NAME = 'Provider'
    _KEY_FIELD = None

class Programme(_Resource):
    id: int
    url: str
    slug: Optional[str]
    title: str
    summary: Optional[str]
    tuition: Tuition
    duration: Optional[str]
    location: Location
    university: University
    _RESOURCE_NAME = 'Programme'
    _KEY_FIELD = 'id'

class Discipline(_Resource):
    id: str
    count: int
    _RESOURCE_NAME = 'Discipline'
    _KEY_FIELD = 'id'

class University(_Resource):
    id: int
    url: Optional[str]
    name: str
    ranking: Optional[int]
    summary: Optional[str]
    location: Location
    programmes_count: Optional[int]
    scholarships_count: Optional[int]
    _RESOURCE_NAME = 'University'
    _KEY_FIELD = 'id'

class Scholarship(_Resource):
    id: str
    url: str
    slug: str
    grant: Grant
    title: str
    benefits: str
    deadline: str
    provider: Provider
    description: str
    discipline_ids: List[str]
    application_basis: Optional[str]
    origin_country_ids: List[str]
    is_deadline_specified: bool
    destination_country_ids: List[str]
    _RESOURCE_NAME = 'Scholarship'
    _KEY_FIELD = 'id'
    _CONSTRUCTIBLE = True

    def details(self) -> ScholarshipDetail:
        """
        Get detailed information for a specific scholarship by its ID and slug. Returns structured data including about text, eligibility summary, and JSON-LD metadata. The id and slug are obtained from search_scholarships results.
        """
        _params: Dict[str, Any] = {}
        _params['id'] = self.id
        _params['slug'] = self.slug
        
        _resp = self._api._request('GET', 'get_scholarship_details', _params)
        return _coerce(_resp, 'ScholarshipDetail', self, mode='return')

class ScholarshipDetail(_Resource):
    id: str
    url: str
    slug: str
    about: str
    json_ld: List[Dict[str, Any]]
    eligibility_summary: str
    _RESOURCE_NAME = 'ScholarshipDetail'
    _KEY_FIELD = 'id'

class ScholarshipPortalCountriesCollection(_Collection):
    def list(self, study_level: Optional[StudyLevel | Literal['phd', 'master', 'bachelor']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Country]:
        """
        Retrieve the list of available countries and their programme counts for a given study level. Useful for discovering valid country_iso values for search filters on search_scholarships and search_programmes.

        Args:
            study_level: Study level context. Accepted values: master, bachelor, phd.
        """
        _params: Dict[str, Any] = {}
        if study_level is not None: _params['study_level'] = study_level
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_countries_list', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Country', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ScholarshipPortalProgrammesCollection(_Collection):
    def search(self, query: Optional[str] = None, offset: Optional[int] = None, country_iso: Optional[str] = None, study_level: Optional[StudyLevel | Literal['phd', 'master', 'bachelor']] = None, discipline_ids: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Programme]:
        """
        Search for academic programmes (MSc, PhD, etc.) with filters for study level, country, discipline, and keyword. Returns paginated results including university, location, tuition, and duration. Pagination is offset-based.

        Args:
            query: Search keyword to filter programmes by title or description.
            offset: Pagination offset (number of results to skip).
            country_iso: Two-letter ISO country code to filter by destination country (e.g. CA, US, GB, NL). Discoverable via get_countries_list.
            study_level: Study level filter. Accepted values: master, bachelor, phd.
            discipline_ids: Comma-separated numeric discipline IDs to filter by field of study. Discoverable via get_disciplines_list.
        """
        _params: Dict[str, Any] = {}
        if query is not None: _params['query'] = query
        if offset is not None: _params['offset'] = offset
        if country_iso is not None: _params['country_iso'] = country_iso
        if study_level is not None: _params['study_level'] = study_level
        if discipline_ids is not None: _params['discipline_ids'] = discipline_ids
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'search_programmes', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Programme', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ScholarshipPortalDisciplinesCollection(_Collection):
    def list(self, study_level: Optional[StudyLevel | Literal['phd', 'master', 'bachelor']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Discipline]:
        """
        Retrieve the list of available academic disciplines and their programme counts for a given study level. Useful for discovering valid discipline_ids values for search filters on search_scholarships and search_programmes.

        Args:
            study_level: Study level context. Accepted values: master, bachelor, phd.
        """
        _params: Dict[str, Any] = {}
        if study_level is not None: _params['study_level'] = study_level
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'get_disciplines_list', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Discipline', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ScholarshipPortalUniversitiesCollection(_Collection):
    def search(self, query: Optional[str] = None, offset: Optional[int] = None, study_level: Optional[StudyLevel | Literal['phd', 'master', 'bachelor']] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[University]:
        """
        Search for universities with optional keyword filter. Returns paginated results with summary, location, ranking, and programme/scholarship counts. Pagination is offset-based.

        Args:
            query: Search keyword to filter universities by name.
            offset: Pagination offset (number of results to skip).
            study_level: Study level filter. Accepted values: master, bachelor, phd.
        """
        _params: Dict[str, Any] = {}
        if query is not None: _params['query'] = query
        if offset is not None: _params['offset'] = offset
        if study_level is not None: _params['study_level'] = study_level
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'search_universities', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'University', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

class ScholarshipPortalScholarshipsCollection(_Collection):
    def search(self, query: Optional[str] = None, offset: Optional[int] = None, country_iso: Optional[str] = None, study_level: Optional[StudyLevel | Literal['phd', 'master', 'bachelor']] = None, discipline_ids: Optional[str] = None, limit: Optional[int] = None, max_fetches: int = 1000) -> _Paginator[Scholarship]:
        """
        Search for scholarships with filters for study level, country, discipline, and keyword. Returns paginated results. Each scholarship includes grant details, deadline, provider info, and a URL slug for fetching full details via get_scholarship_details. Pagination is offset-based; advance by incrementing offset by limit.

        Args:
            query: Search keyword to filter scholarships by title or description.
            offset: Pagination offset (number of results to skip).
            country_iso: Two-letter ISO country code to filter by destination country (e.g. CA, US, GB, NL). Discoverable via get_countries_list.
            study_level: Study level filter. Accepted values: master, bachelor, phd.
            discipline_ids: Comma-separated numeric discipline IDs to filter by field of study. Discoverable via get_disciplines_list.
        """
        _params: Dict[str, Any] = {}
        if query is not None: _params['query'] = query
        if offset is not None: _params['offset'] = offset
        if country_iso is not None: _params['country_iso'] = country_iso
        if study_level is not None: _params['study_level'] = study_level
        if discipline_ids is not None: _params['discipline_ids'] = discipline_ids
        
        def _fetch_page(_cursor: Optional[Any]):
            _p = dict(_params)
            _resp = self._api._request('GET', 'search_scholarships', _p)
            items = _extract_items(_resp, 'items')
            return ([_coerce(_i, 'Scholarship', self, mode='element') for _i in items], None)
        return _Paginator(_fetch_page, limit=limit, max_fetches=max_fetches, _api=self._api)

# Resource registry — populated below so each Resource class can resolve
# nested types during _from_payload coercion.
_RESOURCE_CLASSES: Dict[str, type] = {
    'Grant': Grant,
    'Country': Country,
    'Tuition': Tuition,
    'Location': Location,
    'Provider': Provider,
    'Programme': Programme,
    'Discipline': Discipline,
    'University': University,
    'Scholarship': Scholarship,
    'ScholarshipDetail': ScholarshipDetail,
}

for _cls in _RESOURCE_CLASSES.values():
    _cls._RESOURCE_REGISTRY = _RESOURCE_CLASSES


class ScholarshipPortal(_BaseAPI):
    """
    Search scholarships, academic programmes, universities, and get reference data (countries, disciplines) from StudyPortals/ScholarshipPortal.
    """
    SCRAPER_ID: ClassVar[str] = 'd8ac1888-45af-4a2b-9aee-a54938204f94'
    PINNED_VERSION: ClassVar[Optional[int]] = 8
    _ERROR_CLASSES: ClassVar[Dict[str, type]] = {'input_not_found': ScholarshipNotFound}

    @property
    def countries(self) -> 'ScholarshipPortalCountriesCollection':
        return ScholarshipPortalCountriesCollection(_api=self, _parent=None)

    @property
    def programmes(self) -> 'ScholarshipPortalProgrammesCollection':
        return ScholarshipPortalProgrammesCollection(_api=self, _parent=None)

    @property
    def disciplines(self) -> 'ScholarshipPortalDisciplinesCollection':
        return ScholarshipPortalDisciplinesCollection(_api=self, _parent=None)

    @property
    def universities(self) -> 'ScholarshipPortalUniversitiesCollection':
        return ScholarshipPortalUniversitiesCollection(_api=self, _parent=None)

    @property
    def scholarships(self) -> 'ScholarshipPortalScholarshipsCollection':
        return ScholarshipPortalScholarshipsCollection(_api=self, _parent=None)

__all__ = [
    'ScholarshipPortal',
    'Grant',
    'Country',
    'Tuition',
    'Location',
    'Provider',
    'Programme',
    'Discipline',
    'University',
    'Scholarship',
    'ScholarshipDetail',
    'StudyLevel',
    'ScholarshipNotFound',
    'ParseError',
    'AuthError',
    'ForbiddenError',
    'NotFoundError',
    'BadRequestError',
    'QuotaExceededError',
    'RateLimitError',
    'UpstreamError',
    'PaginationError',
    'PaginationLimitError',
]
