# Generated by `parse sync` — edits will be overwritten. Edit the API in Parse.
from parse_apis.scholarshipportal_com_api import ScholarshipPortal, StudyLevel

portal = ScholarshipPortal()

# Discover available countries for master's programmes
for country in portal.countries.list(study_level=StudyLevel.MASTER):
    print(country.iso, country.count)

# Search for scholarships in the US
for scholarship in portal.scholarships.search(study_level=StudyLevel.MASTER, country_iso="US"):
    print(scholarship.title, scholarship.deadline, scholarship.benefits)
    # Get detailed info for the scholarship
    detail = scholarship.details()
    print(detail.about, detail.eligibility_summary)

# Search for computer science programmes in the Netherlands
for programme in portal.programmes.search(query="computer science", country_iso="NL", study_level=StudyLevel.MASTER):
    print(programme.title, programme.duration, programme.url)

# Search for universities
for uni in portal.universities.search(query="Oxford", study_level=StudyLevel.MASTER):
    print(uni.name, uni.ranking, uni.programmes_count)
